#!/bin/bash

mysql --user=root --password=879574764 << eof

USE QuestionSystem;

DROP TABLE RightsTable;

CREATE TABLE RightsTable(
     ID INT,
     Rights VARCHAR(50)
   );

INSERT INTO RightsTable (ID,Rights) VALUES (0,'|publish|view');

eof
