#!/bin/bash

mysql --user=root --password=879574764 << eof

USE QuestionSystem;

INSERT INTO RightsTable (ID,Rights) VALUES (0,'|publish');
INSERT INTO PersonalInformation (ID,Name) VALUES (0,'hehe');

eof
