#!/bin/bash

mysql --user=root --password=879574764 << eof

#delete QuestionSystem database

DROP DATABASE QuestionSystem;

eof

mysql --user=root --password=879574764 << eof

#init QuestionSystem database

CREATE DATABASE QuestionSystem;

USE QuestionSystem;

CREATE TABLE USER(
     ID INT AUTO_INCREMENT primary key,
     username VARCHAR(20) not null unique
   );

CREATE TABLE SHADOW(
     ID INT AUTO_INCREMENT primary key references USER(ID),
     shadow VARCHAR(20) not null
    );

CREATE TABLE RightsTable(
     ID INT AUTO_INCREMENT primary key,
     Rights VARCHAR(50)
   );

CREATE TABLE ITEM(
     ID INT AUTO_INCREMENT primary key,
     title VARCHAR(200) not null unique,
     description VARCHAR(1000) not null,
     price INT,
     authorID INT references USER(ID)
   );

CREATE TABLE ORDER(
     ID INT AUTO_INCREMENT primary key,
     itemID INT not null references QUESTION(ID),
     authorID INT not null references USER(ID),
   );
eof
