#!/bin/bash

mysql --user=root --password=879574764 << eof

#delete QuestionSystem database

DROP DATABASE QuestionSystem;

eof

mysql --user=root --password=879574764 << eof

#init QuestionSystem database

CREATE DATABASE QuestionSystem;

USE QuestionSystem;

CREATE TABLE PersonalInformation(
     ID INT not null primary key,
     Name VARCHAR(20),
     Graph INT,
     PhoneNumber INT,
     Score INT
   );

CREATE TABLE ShadowTable(
     ID INT not null primary key,
     Shadow VARCHAR(20)
   );

CREATE TABLE RightsTable(
     ID INT not null primary key,
     Rights VARCHAR(50)
   );

CREATE TABLE AskQuestionTable(
     ID INT not null primary key,
     title VARCHAR(200),
     description VARCHAR(1000),
     total_score INT,
     time VARCHAR(20),
     authorID INT
   );

CREATE TABLE AnswerTable(
     ID INT not null primary key,
     questionID INT,
     userID INT,
     answer VARCHAR(1000),
     score INT,
     state INT
   );
eof
